### ISSUE TITLE
Jump animation and Collision

### ISSUE THREAD

**Issue by Cyzox** [Blinking-Eye/Annex#12]
If you run off the platform and then run back into it holding towards it, Mega Man continues the jumping animation again and again. I assume it happens because there is no ground registered below him. Can we set the jump animation to only happen when The key is pressed to jump?

Also, the shooting animation needs to have priority over the jump animation when MM is in the air. We don't have to worry about the transition between the two right now since the sprites will be different. Just something to keep in mind.

**Comment by brcolli** [comment]
I'm aware of the shooting thing, just ignore any possible animations that are lacking. I have the sprites but I'm just lazy.
Also, I want to have a single animation frame (the fall frame) run until he hits the ground. Also, your assumption was right. But the way I have this implemented, specifically to make double jumps work, I need it to run when the ground check on Annex is false. However, since I'm going to make it so that he hangs on one animation frame, it should look fine.

**Comment by brcolli** [comment]
Problem solved.
Also, IDK if you've noticed, but the animations don't come out very snappy sometimes. That's an issue with Unity and I'm trying to find a solution, but IDK if I can....I notice it really bad when you jump and your idle pose is there for a frame or two.
